name: Deploy website

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md' # Ignore changes to README.md
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install 

      - name: Build Astro website 
        run: yarn build 

      - name: Deploy and Reload Caddy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            rsync -avzr --delete $GITHUB_WORKSPACE/dist/ ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/kjelsrud.dev/
            sudo systemctl reload caddy
